---
name: lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    - name: install spell checkers
      run: sudo apt-get install -y enchant aspell
    - name: caching pip downloads
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: python-pip-linter-${{ runner.os }}-3.9
    - name: caching linters caches
      uses: actions/cache@v2
      with:
        path: |
          pylint-home
          .mypy_cache
        key: python-linter-cache-${{ runner.os }}-3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade --upgrade-strategy eager pip
        python -m pip install --upgrade --upgrade-strategy eager black dlint flake8 isort mypy pylint safety bandit pyenchant
    - name: Lint with flake8
      run: |
        flake8 --show-source --statistics src/ghaudit
    - name: Lint with pylint
      if: always()
      run: |
        PYLINTHOME=pylint-home pylint --enable spelling --spelling-dict en_GB src/ghaudit
    - name: Lint with isort
      if: always()
      run: |
        isort --profile black --check-only src/ghaudit
    - name: Analyse with mypy
      if: always()
      run: |
        mypy --strict --pretty src/ghaudit
    - name: Check with safety
      if: always()
      run: |
        safety check
    - name: check coding style
      if: always()
      run: |
        black --diff --check src/ghaudit
