---
name: lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    # - name: install spell checkers
    #   run: sudo apt-get install -y enchant aspell
    - name: caching pip downloads
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: python-pip-linter-${{ runner.os }}-3.10
    - name: caching linters caches
      uses: actions/cache@v2
      with:
        path: |
          pylint-home
          .mypy_cache
        key: python-linter-cache-${{ runner.os }}-3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade --upgrade-strategy eager pip
        python -m pip install --upgrade --upgrade-strategy eager bandit black dlint flake8 flake8-bugbear flake8-comprehensions flake8-isort flake8-pie flake8-typing-imports hypothesis mypy==0.931 pylint pyproject-flake8 safety types-jinja2 types-passpy types-requests
        python -m pip install .
    - name: Check code with Bandit
      if: always()
      run: |
        bandit -r src/ghaudit
    - name: Check vulnerabilities with safety
      if: always()
      run: |
        safety check
    - name: Lint with flake8
      if: always()
      run: |
        pflake8 --show-source --statistics src/ghaudit tests
    - name: Lint with pylint
      if: always()
      run: |
        PYLINTHOME=pylint-home pylint --fail-under 9.65 src/ghaudit tests
    - name: Analyse with mypy
      if: always()
      run: |
        mypy
    - name: check coding style
      if: always()
      run: |
        black --diff --check src/ghaudit tests
